import logging
from environs import Env


env = Env()
env.read_env()

POSTGRES_USER = env.str('POSTGRES_USER')
POSTGRES_PASSWORD = env.str('POSTGRES_PASSWORD')
POSTGRES_HOST = env.str('POSTGRES_HOST')  # no default!
POSTGRES_PORT = env.int('POSTGRES_PORT', 5432)
POSTGRES_DATABASE = env.str('POSTGRES_DATABASE')
TOP_REFERRAL_SOURCES_N = env.int('TOP_REFERRAL_SOURCES_N', 10)
SCHEDULED_MESSAGE_CHECK_FREQUENCY_MIN = env.int('SCHEDULED_MESSAGE_CHECK_FREQUENCY_MIN', 60)
SEND_SCHEDULED_CHUNK_SIZE = env.int("SEND_SCHEDULED_CHUNK_SIZE", 50)
BOT_TOKEN = env.str('BOT_TOKEN')
CHANNEL_USERNAME = env.str('CHANNEL_USERNAME', '')
CHANNEL_ID = env.str("CHANNEL_ID", '')
BOT_ADMINS = tuple(int(chat_id) for chat_id in env.list('BOT_ADMINS', []))

BOT_LOG_LVL = logging._nameToLevel.get(env.str('BOT_LOG_LVL', 'INFO'))
BOT_LOG_FILENAME = env.str('BOT_LOG_FILENAME', None)

COMMUNITY_URL = env.str('COMMUNITY_URL', '')
SUPPORT_URL = env.str('SUPPORT_URL', '')
REGISTRATION_URL = env.str('REGISTRATION_URL', '')
WEBAPP_URL = env.str('WEBAPP_URL', '')
BONUS_TRANSFER_URL = env.str('BONUS_TRANSFER_URL', '')
RESOURCE_NAME = env.str('RESOURCE_NAME', 'Bonus Assistant')


BONUSES_PER_PAGE = env.int('BONUSES_PER_PAGE', 2)
BONUS_REQUESTS_PER_PAGE = env.int('BONUS_REQUESTS_PER_PAGE', 2)
ALL_BONUS_REQUESTS_PER_PAGE = env.int('ALL_BONUS_REQUESTS_PER_PAGE', 2)
USERS_PER_PAGE = env.int('USERS_PER_PAGE', 2)